version: '3.8'

services:
  database:
    image: mariadb:10.7.3
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=rootPassword
      - MARIADB_USER=gamingUser
      - MARIADB_PASSWORD=gamingPassword